<?php

namespace SteveEdson\Invoice;

use Stripe\Charge;
use Stripe\Customer;
use Stripe\Stripe;

class InvoiceManager {

    public $db;
    public $stripe_api_key;

    /**
     * @param \PDO $db Database instance
     * @param $stripe_api_key Stripe Secret API key
     */
    function __construct(\PDO $db, $stripe_api_key) {
        $this->db = $db;
        $this->stripe_api_key = $stripe_api_key;

        // Set the secret api key to be used
        Stripe::setApiKey($this->stripe_api_key);
    }

    /**
     * Get unpaid invoices belonging to an account
     *
     * @param $account_id
     * @return Invoice[]
     */
    public function getUnpaidInvoicesForAccount($account_id) {
        $statement = $this->db->prepare("SELECT *
                                         FROM invoice
                                         WHERE account_id = :account_id
                                          AND status = 'UNPAID'");

        $result = $statement->execute([
            "account_id" => $account_id
        ]);

        if($result) {
            // Fetch records as an array of Invoice objects
            $invoices = $statement->fetchAll(\PDO::FETCH_CLASS, 'SteveEdson\Invoice\Invoice');
        }

        return $invoices;
    }

    /**
     * Get all invoices belonging to an account
     *
     * @param $account_id
     * @return Invoice[]
     */
    public function getInvoicesForAccount($account_id) {
        $statement = $this->db->prepare("SELECT *
                                         FROM invoice
                                         WHERE account_id = :account_id");

        $result = $statement->execute([
            "account_id" => $account_id
        ]);

        if($result) {
            $invoices = $statement->fetchAll(\PDO::FETCH_CLASS, 'SteveEdson\Invoice\Invoice');
        }

        return $invoices;
    }


    /**
     * @param $account_id
     * @param $invoice_id
     * @return Invoice|false
     */
    public function getUserInvoice($account_id, $invoice_id) {
        $statement = $this->db->prepare("SELECT *
                                         FROM invoice
                                         WHERE account_id = :account_id
                                          AND id = :invoice_id
                                         LIMIT 1");

        $result = $statement->execute([
            "account_id" => $account_id,
            "invoice_id" => $invoice_id
        ]);

        if($result) {

            if($statement->rowCount() == 1) {
                return $statement->fetchObject('SteveEdson\Invoice\Invoice');
            } else {
                return false;
            }

        } else {
            return false;
        }
    }

    /**
     * Retrieve a Stripe charge object, using the charge ID
     *
     * @param $charge_id
     * @return Charge
     */
    public function getCharge($charge_id) {
        return Charge::retrieve($charge_id);
    }

    /**
     * Create a Stripe customer and create a charge
     *
     * @param $account_id   Account ID of the user
     * @param $invoice_id   Invoice ID to be paid
     * @param $stripe_token Token generated by Stripe js or Checkout js
     * @param $token_type   Type of token, e.g. card
     * @param $token_email  Email address of Stripe user
     * @return Charge
     */
    public function payInvoice($account_id, $invoice_id, $stripe_token, $token_type, $token_email) {

        // Get the invoice to be paid
        $invoice = $this->getUserInvoice($account_id, $invoice_id);

        // Create the stripe customer
        $customer = Customer::create(array(
            'email' => $token_email,
            'card'  => $stripe_token
        ));

        // Create the charge
        $charge = Charge::create(array(
            'customer' => $customer->id,
            'amount' => $invoice->getAmount(),
            'currency' => 'gbp'
        ));

        if($charge) {
            // Update the database, set the invoice as paid, and store the date and charge ID
            $statement = $this->db
                ->prepare('UPDATE invoice
                           SET status = "PAID",
                               payment_date = now(),
                               stripe_charge = :charge
                           WHERE id = :id');

            // Execute the query with the data
            $statement->execute(array(
                'id' => $invoice_id,
                'charge' => $charge->id
            ));
        }

        return $charge;
    }
}